name: multi job pipeline

on: push
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: build step
      run: echo "Building project"

  test: 
    runs-on: ubuntu-latest

    steps:
    - name: test step
      run: echo "test project"

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: build step
      run : echo "project deploy successfully"

