name: First CI Pipeline

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Print Hello
        run: echo "Hello from CI 🚀"

      - name: Step 2 - Check System
        run: uname -a

      - name: Step 3 - Fixed Step
        run: echo "Step is working fine ✅"